"""
Report Generator Service.
Generates PDF and DOCX/RTF files for incident reports in pure Python, 
avoiding external C-dependencies that might fail in serverless or Windows environments.
"""

import datetime
from typing import Dict, Any

def generate_incident_pdf(incident: Dict[str, Any]) -> bytes:
    """
    Generates a valid PDF document containing incident details using pure Python.
    """
    title = incident.get("title", "Safety Incident Report")
    description = incident.get("description", "No description provided.")
    incident_type = incident.get("incident_type", "Harassment").upper()
    severity = incident.get("severity", "medium").upper()
    status = incident.get("status", "reported").upper()
    
    location_dict = incident.get("location") or {}
    location = location_dict.get("address", "Not specified")
    
    ai_summary = incident.get("ai_summary", "No summary available.")
    timeline = incident.get("ai_timeline", [])
    actions = incident.get("recommended_actions", [])
    
    created_at = incident.get("created_at", datetime.datetime.now().isoformat())
    
    # Construct a simple PDF layout
    pdf_content = []
    
    # PDF Header
    pdf_content.append("%PDF-1.4")
    
    # Font and styles definition
    # Object 1: Catalog
    pdf_content.append("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj")
    
    # Object 2: Pages list
    pdf_content.append("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj")
    
    # Page content stream layout
    text_lines = [
        "----------------------------------------------------------------",
        f"SURAKSHA AI PLATFORM - INCIDENT REPORT",
        "----------------------------------------------------------------",
        f"Incident ID:  {incident.get('id', 'N/A')}",
        f"Reported At:  {created_at}",
        f"Status:       {status} | Severity: {severity}",
        f"Category:     {incident_type}",
        f"Location:     {location}",
        "",
        "TITLE:",
        f"  {title}",
        "",
        "DESCRIPTION:",
        f"  {description[:300]}",
    ]
    if len(description) > 300:
        text_lines.append(f"  {description[300:600]}")
        
    text_lines.extend([
        "",
        "AI INCIDENT ANALYSIS SUMMARY:",
        f"  {ai_summary[:300]}",
    ])
    if len(ai_summary) > 300:
        text_lines.append(f"  {ai_summary[300:600]}")
        
    if timeline:
        text_lines.extend(["", "AI RECONSTRUCTED TIMELINE:"])
        for idx, event in enumerate(timeline[:5]):
            ts = event.get("timestamp", "00:00")
            ev = event.get("event", "Event")
            text_lines.append(f"  [{ts}] {ev[:60]}")
            
    if actions:
        text_lines.extend(["", "RECOMMENDED LEGAL & SAFETY ACTIONS:"])
        for idx, act in enumerate(actions[:5]):
            text_lines.append(f"  {idx+1}. {act[:70]}")
            
    text_lines.extend([
        "",
        "----------------------------------------------------------------",
        "Generated by SURAKSHA AI Safety Companion. Keep this safe.",
        "----------------------------------------------------------------"
    ])

    # Convert text lines into PDF drawing text operators
    stream_content = []
    stream_content.append("BT")
    stream_content.append("/F1 10 Tf")
    stream_content.append("12 TL")
    stream_content.append("50 750 Td") # Initial margins
    
    for line in text_lines:
        # Escape parenthesis for PDF string format
        escaped_line = line.replace("(", "\\(").replace(")", "\\)")
        # If line contains Unicode, encode as ascii or replace
        escaped_line = escaped_line.encode("ascii", "ignore").decode("ascii")
        stream_content.append(f"({escaped_line}) Tj T*")
        
    stream_content.append("ET")
    
    stream_str = "\n".join(stream_content)
    stream_len = len(stream_str)
    
    # Object 4: Contents stream
    pdf_content.append(f"4 0 obj\n<< /Length {stream_len} >>\nstream\n{stream_str}\nendstream\nendobj")
    
    # Object 5: Fonts
    pdf_content.append("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>\nendobj")
    
    # Object 3: Page definition
    pdf_content.append("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj")
    
    # Cross reference table
    pdf_content.append("xref\n0 6\n0000000000 65535 f \n")
    
    # Trailer
    pdf_content.append("trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n10\n%%EOF")
    
    full_pdf = "\n".join(pdf_content)
    return full_pdf.encode("utf-8", "ignore")


def generate_incident_docx(incident: Dict[str, Any]) -> bytes:
    """
    Generates a Rich Text Format (RTF) byte stream.
    Word/Vercel opens RTF with a .docx extension seamlessly as a Word file, 
    allowing pure-Python formatting with colors and tables.
    """
    title = incident.get("title", "Safety Incident Report")
    description = incident.get("description", "No description provided.")
    incident_type = incident.get("incident_type", "Harassment").upper()
    severity = incident.get("severity", "medium").upper()
    status = incident.get("status", "reported").upper()
    
    location_dict = incident.get("location") or {}
    location = location_dict.get("address", "Not specified")
    
    ai_summary = incident.get("ai_summary", "No summary available.")
    timeline = incident.get("ai_timeline", [])
    actions = incident.get("recommended_actions", [])
    
    created_at = incident.get("created_at", datetime.datetime.now().isoformat())

    # Build RTF document
    rtf = []
    rtf.append(r"{\rtf1\ansi\deff0")
    rtf.append(r"{\fonttbl{\f0\fnil\fcharset0 Arial;}{\f1\fmodern\fcharset0 Courier New;}}")
    rtf.append(r"{\colortbl ;\red127\green0\blue0;\red0\green0\blue127;\red100\green100\blue100;}")
    
    # Document header
    rtf.append(r"\b\fs32 SURAKSHA Safety Incident Report\b0\par")
    rtf.append(r"\cf3 Generated on: " + created_at + r"\cf0\par")
    rtf.append(r"====================================================\par\par")
    
    # Metadata fields
    rtf.append(r"\b Incident Title:\b0  " + title + r"\par")
    rtf.append(r"\b Incident Type:\b0  " + incident_type + r"\par")
    rtf.append(r"\b Severity:\b0  \cf1 " + severity + r"\cf0\par")
    rtf.append(r"\b Status:\b0  \cf2 " + status + r"\cf0\par")
    rtf.append(r"\b Location:\b0  " + location + r"\par\par")
    
    # Description
    rtf.append(r"\b\fs24 Details & Description:\b0\fs20\par")
    rtf.append(description.replace("\n", r"\par") + r"\par\par")
    
    # AI Summary
    rtf.append(r"\b\fs24 AI Incident Analysis Summary:\b0\fs20\par")
    rtf.append(ai_summary.replace("\n", r"\par") + r"\par\par")
    
    # Reconstructed timeline
    if timeline:
        rtf.append(r"\b\fs24 AI Reconstructed Timeline:\b0\fs20\par")
        for event in timeline:
            ts = event.get("timestamp", "00:00")
            ev = event.get("event", "Event")
            rtf.append(r"\f1  [" + ts + r"] " + ev + r"\f0\par")
        rtf.append(r"\par")
        
    # Actions
    if actions:
        rtf.append(r"\b\fs24 Recommended Legal & Safety Actions:\b0\fs20\par")
        for idx, act in enumerate(actions):
            rtf.append(f"  {idx+1}. {act}\\par")
        rtf.append(r"\par")
        
    rtf.append(r"====================================================\par")
    rtf.append(r"\i SURAKSHA AI Women Safety Companion - confidential report\i0\par")
    rtf.append(r"}")
    
    full_rtf = "".join(rtf)
    return full_rtf.encode("ascii", "ignore")
