import { create } from 'zustand'

export const SUPPORTED_LANGUAGES = [
  { code: 'en', bcp47: 'en-IN', name: 'English', native: 'English' },
  { code: 'hi', bcp47: 'hi-IN', name: 'Hindi', native: 'हिन्दी' },
  { code: 'ta', bcp47: 'ta-IN', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', bcp47: 'te-IN', name: 'Telugu', native: 'తెలుగు' },
  { code: 'kn', bcp47: 'kn-IN', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'bn', bcp47: 'bn-IN', name: 'Bengali', native: 'বাংলা' },
  { code: 'mr', bcp47: 'mr-IN', name: 'Marathi', native: 'मराठी' },
]

export const TRANSLATIONS = {
  en: {
    app_name: 'SURAKSHA',
    tagline: 'Safe Companion',
    dashboard: 'Dashboard',
    journey_monitor: 'Journey Monitor',
    sos_center: 'SOS Center',
    ai_assistant: 'AI Assistant',
    trust_circle: 'Trust Circle',
    incidents: 'Incidents',
    analytics: 'Analytics',
    profile: 'Profile',
    select_language: 'Select Language',
    start_journey: 'Start Journey',
    end_journey: 'End Journey',
    safe_arrival_confirm: 'Safe Arrival Confirmation',
    voice_sos: 'Voice SOS',
    manual_sos: 'Manual SOS',
    offline_sos: 'Offline SOS',
    online_sos: 'Online SOS',
    secure_tracking_link: 'Secure Tracking Link',
    copy_link: 'Copy Link',
    share_whatsapp: 'Share on WhatsApp',
    listening_keyword: 'Listening for keyword: "Help me SURAKSHA"',
    start_listening: 'Enable Voice SOS',
    stop_listening: 'Disable Voice SOS',
    speak_question: 'Speak your question...',
    read_aloud: 'Listen',
  },
  hi: {
    app_name: 'सुरक्षा (SURAKSHA)',
    tagline: 'सुरक्षित साथी (Safe Companion)',
    dashboard: 'डैशबोर्ड',
    journey_monitor: 'यात्रा निगरानी',
    sos_center: 'आपातकालीन केंद्र (SOS)',
    ai_assistant: 'एआई सहायक (Chitti)',
    trust_circle: 'विश्वास चक्र (Trust Circle)',
    incidents: 'घटनाएँ',
    analytics: 'एनालिटिक्स',
    profile: 'प्रोफ़ाइल',
    select_language: 'भाषा चुनें',
    start_journey: 'यात्रा शुरू करें',
    end_journey: 'यात्रा समाप्त करें',
    safe_arrival_confirm: 'सुरक्षित आगमन पुष्टि',
    voice_sos: 'वॉइस एसओएस',
    manual_sos: 'मैन्युअल एसओएस',
    offline_sos: 'ऑफ़लाइन एसओएस',
    online_sos: 'ऑनलाइन एसओएस',
    secure_tracking_link: 'सुरक्षित ट्रैकिंग लिंक',
    copy_link: 'लिंक कॉपी करें',
    share_whatsapp: 'व्हाट्सएप पर साझा करें',
    listening_keyword: 'कीवर्ड सुन रहे हैं: "सुरक्षा बचाओ"',
    start_listening: 'वॉइस एसओएस चालू करें',
    stop_listening: 'वॉइस एसओएस बंद करें',
    speak_question: 'अपना सवाल बोलें...',
    read_aloud: 'सुनें',
  },
  ta: {
    app_name: 'சுரக்ஷா (SURAKSHA)',
    tagline: 'பாதுகாப்பு தோழன் (Safe Companion)',
    dashboard: 'டாஷ்போர்டு',
    journey_monitor: 'பயண கண்காணிப்பு',
    sos_center: 'அவசர SOS மையம்',
    ai_assistant: 'AI உதவியாளர் (Chitti)',
    trust_circle: 'நம்பிக்கை வட்டம் (Trust Circle)',
    incidents: 'சம்பவங்கள்',
    analytics: 'பகுப்பாய்வு',
    profile: 'சுயவிவரம்',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    start_journey: 'பயணத்தைத் தொடங்கு',
    end_journey: 'பயணத்தை முடி',
    safe_arrival_confirm: 'பாதுகாப்பான வருகை உறுதிப்படுத்தல்',
    voice_sos: 'குரல் SOS',
    manual_sos: 'கையேடு SOS',
    offline_sos: 'ஆஃப்லைன் SOS',
    online_sos: 'ஆன்லைன் SOS',
    secure_tracking_link: 'பாதுகாப்பான கண்காணிப்பு இணைப்பு',
    copy_link: 'இணைப்பை நகலெடு',
    share_whatsapp: 'வாட்ஸ்அப்பில் பகிரவும்',
    listening_keyword: 'முக்கிய சொல்லை கேட்கிறது: "Help me SURAKSHA"',
    start_listening: 'குரல் SOS ஐ இயக்கு',
    stop_listening: 'குரல் SOS ஐ முடக்கு',
    speak_question: 'உங்கள் கேள்வியைப் பேசுங்கள்...',
    read_aloud: 'கேளுங்கள்',
  },
  te: {
    app_name: 'సురక్ష (SURAKSHA)',
    tagline: 'రక్షక సహచరుడు (Safe Companion)',
    dashboard: 'డ్యాష్‌బోర్డ్',
    journey_monitor: 'ప్రయాణ పర్యవేక్షణ',
    sos_center: 'అత్యవసర కేంద్రం (SOS)',
    ai_assistant: 'AI సహాయకుడు (Chitti)',
    trust_circle: 'విశ్వాస వలయం (Trust Circle)',
    incidents: 'సంఘటనలు',
    analytics: 'విశ్లేషణలు',
    profile: 'ప్రొఫైల్',
    select_language: 'భాషను ఎంచుకోండి',
    start_journey: 'ప్రయాణం ప్రారంభించండి',
    end_journey: 'ప్రయాణం ముగించండి',
    safe_arrival_confirm: 'సురక్షిత రాక నిర్ధారణ',
    voice_sos: 'వాయిస్ SOS',
    manual_sos: 'మాన్యువల్ SOS',
    offline_sos: 'ఆఫ్‌లైన్ SOS',
    online_sos: 'ఆన్‌లైన్ SOS',
    secure_tracking_link: 'సురక్షిత ట్రాకింగ్ లింక్',
    copy_link: 'లింక్ కాపీ చేయండి',
    share_whatsapp: 'వాట్సాప్‌లో షేర్ చేయండి',
    listening_keyword: 'కీవర్డ్ వింటుంది: "నన్ను కాపాడండి SURAKSHA"',
    start_listening: 'వాయిస్ SOS ప్రారంభించండి',
    stop_listening: 'వాయిస్ SOS ఆపండి',
    speak_question: 'మీ ప్రశ్నను మాట్లాడండి...',
    read_aloud: 'వినండి',
  },
  kn: {
    app_name: 'ಸುರಕ್ಷಾ (SURAKSHA)',
    tagline: 'ಸುರಕ್ಷಿತ ಒಡನಾಡಿ (Safe Companion)',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    journey_monitor: 'ಪ್ರಯಾಣ ಮೇಲ್ವಿಚಾರಣೆ',
    sos_center: 'ತುರ್ತು ಕೇಂದ್ರ (SOS)',
    ai_assistant: 'ಎಐ ಸಹಾಯಕ (Chitti)',
    trust_circle: 'ವಿಶ್ವಾಸ ವಲಯ (Trust Circle)',
    incidents: 'ಘಟನೆಗಳು',
    analytics: 'ಅನಾಲಿಟಿಕ್ಸ್',
    profile: 'ಪ್ರೊಫೈಲ್',
    select_language: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    start_journey: 'ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ',
    end_journey: 'ಪ್ರಯಾಣ ಮುಗಿಸಿ',
    safe_arrival_confirm: 'ಸುರಕ್ಷಿತ ಆಗಮನ ದೃಢೀಕರಣ',
    voice_sos: 'ಧ್ವನಿ SOS',
    manual_sos: 'ಹಸ್ತಚಾಲಿತ SOS',
    offline_sos: 'ಆಫ್‌ಲೈನ್ SOS',
    online_sos: 'ಆನ್‌ಲೈನ್ SOS',
    secure_tracking_link: 'ಸುರಕ್ಷಿತ ಟ್ರ್ಯಾಕಿಂಗ್ ಲಿಂಕ್',
    copy_link: 'ಲಿಂಕ್ ನಕಲಿಸಿ',
    share_whatsapp: 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
    listening_keyword: 'ಕೀವರ್ಡ್ ಆಲಿಸುತ್ತಿದೆ: "ನನಗೆ ಸಹಾಯ ಮಾಡಿ SURAKSHA"',
    start_listening: 'ಧ್ವನಿ SOS ಸಕ್ರಿಯಗೊಳಿಸಿ',
    stop_listening: 'ಧ್ವನಿ SOS ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ',
    speak_question: 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಮಾತನಾಡಿ...',
    read_aloud: 'ಆಲಿಸಿ',
  },
  bn: {
    app_name: 'সুরক্ষা (SURAKSHA)',
    tagline: 'নিরাপদ সঙ্গী (Safe Companion)',
    dashboard: 'ড্যাশবোর্ড',
    journey_monitor: 'যাত্রা নজরদারি',
    sos_center: 'জরুরি কেন্দ্র (SOS)',
    ai_assistant: 'এআই সহকারী (Chitti)',
    trust_circle: 'আস্থা বৃত্ত (Trust Circle)',
    incidents: 'ঘটনাসমূহ',
    analytics: 'অ্যানালিটিক্স',
    profile: 'প্রোফাইল',
    select_language: 'ভাষা নির্বাচন করুন',
    start_journey: 'যাত্রা শুরু করুন',
    end_journey: 'যাত্রা শেষ করুন',
    safe_arrival_confirm: 'নিরাপদ আগমন নিশ্চিতকরণ',
    voice_sos: 'ভয়েস এসওএস',
    manual_sos: 'ম্যানুয়াল এসওএস',
    offline_sos: 'অফলাইন এসওএস',
    online_sos: 'অনলাইন এসওএস',
    secure_tracking_link: 'নিরাপদ ট্র্যাকিং লিঙ্ক',
    copy_link: 'লিঙ্ক কপি করুন',
    share_whatsapp: 'হোয়াটসঅ্যাপে শেয়ার করুন',
    listening_keyword: 'কীওয়ার্ড শুনছে: "বাঁচাও SURAKSHA"',
    start_listening: 'ভয়েস এসওএস চালু করুন',
    stop_listening: 'ভয়েস এসওএস বন্ধ করুন',
    speak_question: 'আপনার প্রশ্ন বলুন...',
    read_aloud: 'শুনুন',
  },
  mr: {
    app_name: 'सुरक्षा (SURAKSHA)',
    tagline: 'सुरक्षित साथी (Safe Companion)',
    dashboard: 'डॅशबोर्ड',
    journey_monitor: 'प्रवास देखरेख',
    sos_center: 'आपत्कालीन केंद्र (SOS)',
    ai_assistant: 'एआय सहाय्यक (Chitti)',
    trust_circle: 'विश्वास चक्र (Trust Circle)',
    incidents: 'घटना',
    analytics: 'अॅनालिटिक्स',
    profile: 'प्रोफाइल',
    select_language: 'भाषा निवडा',
    start_journey: 'प्रवास सुरू करा',
    end_journey: 'प्रवास समाप्त करा',
    safe_arrival_confirm: 'सुरक्षित आगमन पुष्टीकरण',
    voice_sos: 'व्हॉइस एसओएस',
    manual_sos: 'मॅन्युअल एसओएस',
    offline_sos: 'ऑफलाइन एसओएस',
    online_sos: 'ऑनलाइन एसओएस',
    secure_tracking_link: 'सुरक्षित ट्रॅकिंग लिंक',
    copy_link: 'दुवा कॉपी करा',
    share_whatsapp: 'व्हॉट्सअॅपवर शेअर करा',
    listening_keyword: 'कीवर्ड ऐकत आहे: "मला मदत करा SURAKSHA"',
    start_listening: 'व्हॉइस एसओएस सक्षम करा',
    stop_listening: 'व्हॉइस एसओएस अक्षम करा',
    speak_question: 'तुमचा प्रश्न बोला...',
    read_aloud: 'ऐका',
  },
}

export const useLanguageStore = create((set, get) => ({
  language: localStorage.getItem('suraksha_lang') || 'en',
  setLanguage: (code) => {
    localStorage.setItem('suraksha_lang', code)
    set({ language: code })
  },
  t: (key) => {
    const lang = get().language
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key
  },
  getLanguageObj: () => {
    const lang = get().language
    return SUPPORTED_LANGUAGES.find((l) => l.code === lang) || SUPPORTED_LANGUAGES[0]
  },
}))
